//actions redux

export const TOGGLE_COLOR_THEME = "TOGGLE_COLOR_THEME";
export const TOGGLE_COLOR_THEME_BLACK = "TOGGLE_COLOR_THEME_BLACK";

export const LOG_IN = "LOG_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const CHANGE_USERNAME = "CHANGE_USERNAME";

export const UPDATE_LOCALIZATION = "UPDATE_LOCALIZATION";
export const DENY_LOCALIZATION = "DENY_LOCALIZATION";

export const CLOSE_WIDGET = "CLOSE_WIDGET";
export const CHANGE_ACTIVE_WIDGET = "CHANGE_ACTIVE_WIDGET";

export const CREATE_NEW_NOTE = "CREATE_NEW_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const DISPLAY_ACTIVE_NOTE = "DISPLAY_ACTIVE_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";

export const SET_DISPLAYED_DAY = "SET_DISPLAYED_DAY";
export const ADD_WEATHER_LOCALIZATION = "ADD_WEATHER_LOCALIZATION";