//actions redux

export const TOGGLE_COLOR_THEME = "TOGGLE_COLOR_THEME";
export const TOGGLE_COLOR_THEME_BLACK = "TOGGLE_COLOR_THEME_BLACK";

export const LOG_IN = "LOG_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const CHANGE_USERNAME = "CHANGE_USERNAME";

export const UPDATE_LOCALIZATION = "UPDATE_LOCALIZATION";
export const DENY_LOCALIZATION = "DENY_LOCALIZATION";

export const CLOSE_WIDGET = "CLOSE_WIDGET";